### ISSUE TITLE
Is it Possible to write CDX?

### ISSUE THREAD

**Issue by mohammali** [Chessforeva/JavaFoxDBF#2]
Dear Chessforeva, 

I am amazed by your code and your knowledge. I have read your warning multiple times and still wonder if it is possible to write a CDX after inserting a new record into a DBF?

I see your note
```
The CDX file writing part is possible to develop, but then this won't work on FoxPro anymore for sure.
```
 
My case:
I want to rewrite a DBF, FPT and CDX after inserting a new record from Java and then this data will be shown in FoxPro application later on. is that possible?

Thank you in advance.

**Comment by Chessforeva** [comment]
Hi.

Actually, foxpro took years of my working life :)
The thing is, foxpro was developed when PCs were very very very slow and
windows didn't even exist.
When foxpro writes indexes internally in other file (.idx) then, in
practice, in many cases disk-write errors occurred and the whole index file
was corrupted.
The .cdx file is a compound index, which was developed by Microsoft years
later, and had even more such cases. because of one large file and larger
chunks to write.
There is no guarantee that writing will do it for 100%. As it is in SQL
server case. Then the whole index file will be lost. It will happen.

So, to avoid this, we wrote foxpro apps working in parallel as SQL server
to be sure.

The open-source also didn't exist then. CDX is Microsoft's property without
any source available.
Nevertheless, there were some serious hacks (a kind of alternative to
foxpro) developed software such as Harbour project, Alaska clipper.
As I remember.
But I didn't like making real .cdx writing, and even .idx seems like a bad
idea.
The .cdx file appends large chunks of blank space and then writes pointers
there and index keys. So, the algorithm then jumps back and forth this file.
Nowadays there are easySQLs. Or, as I prefer, mongoDB where I can store
everything  NoSql databases also.
There is no time to rewrite .cdx oldies of Microsoft, believe me. Worst
architecture ever. Just very cheap then, to avoid buying oracle servers.

If seriously, I can give a windows forpro exe application to run as a
process in the background that does exactly the same DBF,CDX management
without java or pythons.
Just write requests in the folder, the app writes back the data. Intended
for web-servers a long time ago.

Foxpro is dead as a database system. Or just readonly.

Sincerely,
ChessforevaDev

svētd., 2023. g. 3. sept., plkst. 02:57 — lietotājs Mohammad Ali (<
***@***.***>) rakstīja:

**Comment by mohammali** [comment]
Many thanks for your replay I appreciate it
